build/pkgs/cvxopt: set suitesparse lib and include dir for system pacakge
cvxopt SPKG fails to build on systems where suitesparse is installed as
system package:

```
[spkg-install] building 'umfpack' extension
[spkg-install] /home/bagas/miniconda3/envs/sagemath/bin/x86_64-conda-linux-gnu-cc -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/bagas/miniconda3/envs/sagemath/include -fPIC -O2 -isystem /home/bagas/miniconda3/envs/sagemath/include -O2 -march=haswell -mtune=haswell -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/bagas/miniconda3/envs/sagemath/include -fPIC -I/usr/include -I/tmp/build-env-zu8tbe51/include -I/home/bagas/miniconda3/envs/sagemath/include/python3.11 -c src/C/umfpack.c -o build/temp.linux-x86_64-cpython-311/src/C/umfpack.o
[spkg-install] src/C/umfpack.c:23:10: fatal error: umfpack.h: No such file or directory
[spkg-install]    23 | #include "umfpack.h"
[spkg-install]       |          ^~~~~~~~~~~
[spkg-install] compilation terminated.
[spkg-install] error: command '/home/bagas/miniconda3/envs/sagemath/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
[spkg-install]
[spkg-install] ERROR Backend subprocess exited when trying to invoke build_wheel
```

This is because required build variables
($CVXOPT_SUITESPARSE_{LIB,INC}_DIR) don't get set in that case as
$SAGE_SUITESPARSE_PREFIX is empty due to using suitesparse system
package instead.

Set the build variables. For now, this requires suitesparse headers
to be installed in ${SAGE_LOCAL}/include/suitesparse.